name: gigasecond
version: 0.1.0.3

dependencies:
  - base
  - time

library:
  exposed-modules: Gigasecond
  source-dirs: src
  ghc-options: -Wall

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - gigasecond
      - hspec
