name: word-search
version: 1.0.0.0

dependencies:
  - base

library:
  exposed-modules: WordSearch
  source-dirs: src
  ghc-options: -Wall

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - word-search
      - hspec
