name: sublist
version: 1.1.0.6

dependencies:
  - base

library:
  exposed-modules: Sublist
  source-dirs: src
  ghc-options: -Wall

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - sublist
      - hspec
