name: octal
version: 0.1.0.3

dependencies:
  - base

library:
  exposed-modules: Octal
  source-dirs: src
  ghc-options: -Wall

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - octal
      - hspec
      - QuickCheck
