name: simple-cipher
version: 1.2.0.5

dependencies:
  - base
  - random

library:
  exposed-modules: Cipher
  source-dirs: src
  ghc-options: -Wall

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - simple-cipher
      - hspec
