name: binary
version: 0.9.0.3

dependencies:
  - base

library:
  exposed-modules: Binary
  source-dirs: src
  ghc-options: -Wall

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - binary
      - hspec
