name: saddle-points
version: 1.5.0.8

dependencies:
  - array
  - base

library:
  exposed-modules: Matrix
  source-dirs: src
  ghc-options: -Wall

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - saddle-points
      - hspec
