name: bank-account
version: 0.1.0.4

dependencies:
  - base
  - stm # Added stm for concurrent state

library:
  exposed-modules: BankAccount
  source-dirs: src
  ghc-options: -Wall
  dependencies: # Uncommented this section
   - stm       # Added stm dependency for the library

tests:
  test:
    main: Tests.hs
    source-dirs: test
    ghc-options: -threaded -rtsopts -with-rtsopts=-N
    dependencies:
      - bank-account
      - hspec
