name: poker
version: 1.1.0.2

dependencies:
  - base

library:
  exposed-modules: Poker
  source-dirs: src
  ghc-options: -Wall
  dependencies:
   - containers  # For Data.Map and other data structures

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - poker
      - hspec
