name: matching-brackets
version: 2.0.0.8

dependencies:
  - base
  - containers

library:
  exposed-modules: Brackets
  source-dirs: src
  ghc-options: -Wall

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - matching-brackets
      - hspec
