name: matrix
version: 1.3.0.9

dependencies:
  - base
  - vector

library:
  exposed-modules: Matrix
  source-dirs: src
  ghc-options: -Wall

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - matrix
      - hspec
      - QuickCheck
