name: poker
version: 1.1.0.2

dependencies:
  - base
  - containers
  - array

library:
  exposed-modules: Poker
  source-dirs: src
  ghc-options: -Wall

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - poker
      - hspec
