name: ocr-numbers
version: 1.2.0.6

dependencies:
  - base
  # Add containers package dependency here
  - containers

library:
  exposed-modules: OCR
  source-dirs: src
  ghc-options: -Wall
  # dependencies: # Dependencies specific to the library can also go here
  # - foo       # List here the packages you
  # - bar       # want to use in your solution.

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - ocr-numbers
      - hspec
