name: sgf-parsing
version: 1.2.0.5

dependencies:
  - base >=4.14 && <5
  - containers
  - text
  - parsec >=3.1 && <3.2

library:
  exposed-modules: Sgf
  source-dirs: src
  ghc-options: -Wall
  dependencies:
    - base
    - containers
    - text
    - parsec

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - sgf-parsing
      - hspec
