name: armstrong-numbers
version: 1.1.0.3

dependencies:
  - base

library:
  exposed-modules: ArmstrongNumbers
  source-dirs: src
  ghc-options: -Wall

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - armstrong-numbers
      - hspec
