name: etl
version: 2.0.1.6

dependencies:
  - base
  - containers

library:
  exposed-modules: ETL
  source-dirs: src
  ghc-options: -Wall

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - etl
      - hspec
