name: sieve
version: 1.1.0.5

dependencies:
  - base
  - array  # Add the array package dependency here

library:
  exposed-modules: Sieve
  source-dirs: src
  ghc-options: -Wall
  # dependencies: # Dependencies specific to the library can also go here
  # - foo       # List here the packages you
  # - bar       # want to use in your solution.

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - sieve
      - hspec
