name: exercism-clock
version: 2.4.0.10

dependencies:
  - base
  - text

library:
  exposed-modules: Clock
  source-dirs: src
  ghc-options: -Wall

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - exercism-clock
      - hspec
