name: prime-factors
version: 1.1.0.5

dependencies:
  - base

library:
  exposed-modules: PrimeFactors
  source-dirs: src
  ghc-options: -Wall

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - prime-factors
      - hspec
