name: sgf-parsing
version: 1.2.0.5

library:
  source-dirs: src
  exposed-modules:
    - Sgf
  ghc-options: -Wall
  dependencies:
    - base
    - containers
    - text
    - parsec

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - sgf-parsing
      - hspec
