name: simple-linked-list
version: 0.1.0.3

dependencies:
  - base

library:
  exposed-modules: LinkedList
  source-dirs: src
  ghc-options: -Wall

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - simple-linked-list
      - hspec
      - QuickCheck
