name: diamond
version: 1.1.0.6

dependencies:
  - base
  - text

library:
  exposed-modules: Diamond
  source-dirs: src
  ghc-options: -Wall

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - diamond
      - hspec
      - QuickCheck
      - text
