name: allergies
version: 1.2.0.7

dependencies:
  - base
  - base >= 4.7 && < 5
  - containers

library:
  exposed-modules: Allergies
  source-dirs: src
  ghc-options: -Wall

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - allergies
      - hspec
      - QuickCheck
