name: say
version: 1.2.0.6

dependencies:
  - base

library:
  exposed-modules: Say
  source-dirs: src
  ghc-options: -Wall

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - say
      - hspec
