name: two-bucket
version: 1.0.0.0

dependencies:
  - base
  - mtl

library:
  exposed-modules: TwoBucket
  source-dirs: src
  ghc-options: -Wall
  dependencies:
   # Add these:
   - containers
   - sequences

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - two-bucket
      - hspec
