name: rail-fence-cipher
version: 1.1.0.5

dependencies:
  - base

library:
  exposed-modules: RailFenceCipher
  source-dirs: src
  ghc-options: -Wall

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - rail-fence-cipher
      - hspec
