name: resistor-color-trio
version: 1.0.0.0

dependencies:
  - base

library:
  exposed-modules: ResistorColors
  source-dirs: src
  ghc-options: -Wall

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - resistor-color-trio
      - hspec
