name: satellite
version: 1.0.0.0

dependencies:
  - base

library:
  source-dirs: src
  ghc-options: -Wall
  exposed-modules:
    - Satellite (treeFromTraversals)
    - BinaryTree (..)

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - satellite
      - hspec
