name: isogram
version: 1.7.0.8

dependencies:
  - base
  - containers

library:
  exposed-modules: Isogram
  source-dirs: src
  ghc-options: -Wall
  dependencies:
    - base
    - containers

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - isogram
      - hspec
