name: twelve-days
version: 1.2.0.5

dependencies:
  - base
  - text

library:
  exposed-modules: TwelveDays
  source-dirs: src
  ghc-options: -Wall

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - twelve-days
      - hspec
