name: hexadecimal
version: 0.1.0.3

dependencies:
  - base

library:
  exposed-modules: Hexadecimal
  source-dirs: src
  ghc-options: -Wall
  # The Hexadecimal module now implements hexToInt,
  # converting hexadecimal strings to decimal values using first principles.

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - hexadecimal
      - hspec
