name: trinary
version: 0.1.0.3

dependencies:
  - base

library:
  exposed-modules: Trinary
  source-dirs: src
  ghc-options: -Wall

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - trinary
      - hspec
      - QuickCheck
