name: affine-cipher
version: 1.0.0.0

dependencies:
  - base
  - text

library:
  exposed-modules: Affine
  source-dirs: src
  ghc-options: -Wall

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - affine-cipher
      - hspec
