name: sieve
version: 1.1.0.5

dependencies:
  - base
  - array

library:
  exposed-modules: Sieve
  source-dirs: src
  ghc-options: -Wall

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - sieve
      - hspec
