name: zipper
version: 1.1.0.5

dependencies:
  - base

library:
  exposed-modules: Zipper
  source-dirs: src
  ghc-options: -Wall

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - zipper
      - hspec
