name: food-chain
version: 0.1.0.3

dependencies:
  - base

library:
  exposed-modules: FoodChain
  source-dirs: src
  ghc-options: -Wall
  # dependencies:
  # - foo
  # - bar

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - food-chain
      - hspec
