name: sieve
version: 1.1.0.5

dependencies:
  - base
  # Add the array package dependency here for the library
  - array

library:
  exposed-modules: Sieve
  source-dirs: src
  ghc-options: -Wall
  # dependencies: # This section is commented out, dependencies are usually listed at the top level or per-component
  # - foo       # List here the packages you
  # - bar       # want to use in your solution.

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - sieve
      - hspec
      # Tests might also need array if they directly use it, but here they depend on the library 'sieve'
      # which now correctly depends on 'array'.
