name: pov
version: 1.3.0.7

dependencies:
  - base
  - containers

library:
  exposed-modules: POV
  source-dirs: src
  ghc-options: -Wall

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - pov
      - hspec
